### ISSUE TITLE
Using cache causes JS#getModuleIDByOrigin to fail

### ISSUE THREAD

**Issue by amasad** [facebook/node-haste#17]
Calling `JS#getModuleIDByOrigin` depends on `JS#recordRequiredModuleOrigin` which is called in the postProcessing stage of new files after updating the map. Now if the cache is up-to-date, then postProcessing never happens and `JS#getModuleIDByOrigin` will fail.

This materializes in the following way:

1. You have a module in node_modules that is called `ModuleX` and the `main` file is `ModuleX/main.js`
2. When packaging up `ModuleX` to serve to the client, we define the module `ModuleX/main.js`
3. When resolving top-level module names to their respective main files we call `getModuleIDByOrigin` on the resource.
4. If we're using cache then this fails because it returns the same module name

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
