### ISSUE TITLE
Explanation is not clean

### ISSUE THREAD

**Issue by gyzerok** [facebook/node-haste#22]
Hi there!
Since I like most of the FB tecnologiest such as React, React Native, Flow, Immutable I am really interested in this cuz it can be awesome. But your docs didn't give me a clean explanation why should I use node-haste. And your example isn't clean for me at all.

As I understood while using node-haste I can update my js code on the air without restarting node.js. Am I right?

**Comment by zpao** [comment]
You almost certainly shouldn't use node-haste. It's mostly just for module resolution for situations where you are combining providesModule with commonjs. There are some other things its capable of. But it's not actively maintained and bugs won't be addressed in any reasonable time. I strongly suggest forgetting you ever even saw this :)

**Comment by barbu110** [comment]
If this is not actively maintained, is there any other open-source project (even not Facebook-made) to accomplish this mission?
