### ISSUE TITLE
new relic with its invalid json examples is crashing jest

### ISSUE THREAD

**Issue by Jabher** [facebook/node-haste#25]
I have a project where new relic is used. 
When starting jest I'm getting 
```
Error parsing `/Users/jabher/oap/node_modules/newrelic/test/lib/example-packages/invalid-json/package.json`!
/Users/jabher/oap/node_modules/jest-cli/node_modules/node-haste/lib/loader/ProjectConfigurationLoader.js:65
      throw e;
            ^
SyntaxError: Unexpected token a
  at Object.parse (native)
  at ProjectConfigurationLoader.loadFromSource (/Users/jabher/oap/node_modules/jest-cli/node_modules/node-haste/lib/loader/ProjectConfigurationLoader.js:62:46)
  at /Users/jabher/oap/node_modules/jest-cli/node_modules/node-haste/lib/loader/ResourceLoader.js:90:10
  at fs.js:334:14
  at /Users/jabher/oap/node_modules/jest-cli/node_modules/graceful-fs/graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:95:15)
```

Actually, I even do not understand fully what's going on and why every json is installed, but all packages are installed via npm install and I cannot simply remove it from repo, it's coming there every time on project installation.

**Comment by zpao** [comment]
newrelic probably shouldn't be shipping their tests. This isn't a node-haste issue but a jest user issue. You should ignore that path (perhaps all node_modules) with the config.

**Comment by Jabher** [comment]
Yeah, I know, but we all live in real world where some modules are not clean.

Thanks for explanation.
