### ISSUE TITLE
weird use of __proto__

### ISSUE THREAD

**Issue by AceMood** [facebook/node-haste#27]
I notice several places of the code use  <pre>`__proto__`</pre>  instead of inherits method, for example, the Resource and ResourceLoader related Classes. It's an ES6 attribute which indicates the relation between object's constructor's prototype and the object itself, but it's unclear to give this kind of code: 
<pre>CSS.__proto__ = Resource.</pre>
just BECAUSE CSS need the fromObject static method of Resource.

**Comment by zpao** [comment]
Welcome to our old old code that hasn't been updated :) This mostly doesn't matter and will go away so going to close out.

**Comment by AceMood** [comment]
Do you mean the node-Haste is no longer used in your project any more? 
I was very interested in the Static Resource Management System of Facebook, node-Haste is indeed a general way to build a resource map which can be used by several scenarios such as bigpipe and quickling. I think it's a facade. Do you have any other advice to follow your newer solution here?

**Comment by zpao** [comment]
https://github.com/facebook/node-haste/tree/dev has in progress work. This stack is not used in our actual static resources pipeline at FB but primarily in other environments like for Jest where we need to do many of the same things.
