### ISSUE TITLE
Relation between node-Haste and Haste System.

### ISSUE THREAD

**Issue by AceMood** [facebook/node-haste#30]
Hi, Facebook had did the static resource management in its Celerity way. It has been partly open sourced since 2010. So what the relation between node-Haste and Haste and Celerity? Is node-Haste the node version of Haste?  What new features have been added to Haste System from that time? Any new thinking here?

**Comment by cpojer** [comment]
We updated the repo with a new README and we are publishing a new version of node-haste as node-haste 2 soon.
