### ISSUE TITLE
Incremental Caching

### ISSUE THREAD

**Issue by cpojer** [facebook/node-haste#45]
JSON.stringify blows up on www with an OOM because the string to stringify is too big, see https://github.com/facebook/node-haste/blob/master/src/Cache/index.js#L158

repro on www `jest-www --execTestsRelatedTo html/js/ads/powereditor/model/campaign.js --new`.

We need to figure out to store less data in the cache and/or make it more incremental or split it up.

**Comment by cpojer** [comment]
Oh, the problem is that we are storing both `.source` and `.cache` for Modules in the Cache now.

@davidaurelio can you revert this change? We can't store all this data in the cache because it OOMs :)

**Comment by davidaurelio** [comment]
“I need all that data” – I need both source and transform result to build a bundle with source map. 

Maybe we can store these in an optional second cache for the time being, until we store these on the FS.
Would that work for you?

**Comment by cpojer** [comment]
yeah that would work for now as long as its optional. It's just definitely not going to scale for long – you should check what the memory usage is after the transform. `JSON.stringify` just completely blows up with an OOM on www.

See https://github.com/facebook/jest/blob/master/src/lib/transform.js#L104-L112 – if you think that file is useful by itself, we can abstract it out into a `jest-transform` package as part of the jest modularization effort. The first packages will land in Jest soon, so there'll be a guideline for this. See https://github.com/facebook/jest/pull/721

**Comment by cpojer** [comment]
Made it optional in #64. This is fine for now.

**Comment by davidaurelio** [comment]
thanks for taking care of that!
