### ISSUE TITLE
Use the file pattern switch for more than just the platform infixExt

### ISSUE THREAD

**Issue by bartolkaruza** [facebook/node-haste#81]
We are trying to come up with a clean solution for dynamic asset loading, using a similar mechanism as the platform file switch (eg .ios.js and .android.js) but for an arbitrary string (eg file.a.js file.b.js) specified on the packager url (eg -platform=ios&dev=true&infixExt=a). This functionality would allow for all kinds of use cases for multiple apps from a single code base (white label/generated apps).

The additional query parameter (infixExt, anyone can think of a better name?) would require a modification of the packager server in the react-native repo and of node-haste. 

Before we start creating the two PR's, what do you think of this approach? Do we have a chance of getting this merged?

**Comment by brentvatne** [comment]
This sounds like it could potentially be useful! `&infixExt=staging` could be a nice way to include different config files, for example.

I'd like to see it support multiple options though, similar to `assetExts`.

cc @ide @nikki93 @cpojer

**Comment by bartolkaruza** [comment]
We are working on this, also with an array of possible options like assetExts. @davidaurelio has moved node-haste to the react-native repo, so we are trying to move our changes to a PR there.
